### ISSUE TITLE
CC - 03 - skóre 5

### ISSUE THREAD

**Issue by zwn** [robotika/subt-artf#100]
```yaml
world_name: cave_circuit_01
robots:
  A100W900LH700RH3600W:
    platform: X4
    config: SSCI_X4_SENSOR_CONFIG_2
  B700W600LH400RH3600W:
    platform: X4
    config: SSCI_X4_SENSOR_CONFIG_2
  C120W1500RH1300LH3600W:
    platform: FREYJA
    config: ROBOTIKA_FREYJA_SENSOR_CONFIG_2
  D0W1700RH1500LH3600W:
    platform: FREYJA
    config: ROBOTIKA_FREYJA_SENSOR_CONFIG_2
  E60W1750LH1550RH3600W:
    platform: FREYJA
    config: ROBOTIKA_FREYJA_SENSOR_CONFIG_2
  F1000W600RH400LH3600W:
    platform: X4
    config: SSCI_X4_SENSOR_CONFIG_2
  G300W900RH700LH3600W:
    platform: X4
    config: SSCI_X4_SENSOR_CONFIG_2
  H0W1050RH850LH3600W:
    platform: X4
    config: SSCI_X4_SENSOR_CONFIG_2
marsupials:
  {}
artifacts_found: 5
robot_count: 8
unique_robot_count: 2
sim_time: 3600
real_time: 98749
artifact_report_count: 10
duplicate_report_count: 99
closest_artifact_report:
  name: backpack_4
  type: TYPE_BACKPACK
  true_pos: 101.154 -49.8156 0.610234
  reported_pos: 101.28 -50.21 0.67
  distance: 0.4183645844203067
first_artifact_report: 61.408
last_artifact_report: 1910.004
mean_time_between_successful_artifact_reports: 369.7192
greatest_distance_traveled: 1163.628246080696
greatest_distance_traveled_robot: F1000W600RH400LH3600W
greatest_euclidean_distance_from_start: 273.787634557987
greatest_euclidean_distance_from_start_robot: A100W900LH700RH3600W
total_distance_traveled: 4568.373022205942
greatest_max_vel: 10.88568836594646
greatest_max_vel_robot: E60W1750LH1550RH3600W
greatest_avg_vel: 7.560183141603194
greatest_avg_vel_robot: E60W1750LH1550RH3600W
greatest_elevation_gain: 70
greatest_elevation_gain_robot: G300W900RH700LH3600W
greatest_elevation_loss: -65
greatest_elevation_loss_robot: E60W1750LH1550RH3600W
total_elevation_gain: 175
total_elevation_loss: -255
max_elevation_reached: 20
max_elevation_reached_robot: G300W900RH700LH3600W
min_elevation_reached: -30
min_elevation_reached_robot: E60W1750LH1550RH3600W
```
