### ISSUE TITLE
FP2 - ver102dro3d4fp2r1 - 1d198844-65cb-4bd3-b7ef-5a501c18b15c

### ISSUE THREAD

**Issue by m3d** [robotika/subt-artf#136]
Toto byl pokus s Octomapou pro dronu ale oriznutou vysku na 2m a pro Freyju na 0.5m (rozliseni stale 0.5m). Zaroven byl zapojeny novy detektor moznosti detekovat Cube. Proc zacinam tento report je
![saveX-0000](https://user-images.githubusercontent.com/5664353/113816815-a29b8100-9775-11eb-85f4-d074b3cb9165.jpg)
```
0:01:54.292415 received: ['TYPE_BACKPACK', [12462, 6908, 250], 'B600LXM', True]
0:03:22.784210 received: ['TYPE_BACKPACK', [12137, 11253, 230], 'B600LXM', False]
0:03:40.859601 received: ['TYPE_BACKPACK', [14774, 15000, 249], 'B600LXM', False]
0:05:59.908511 received: ['TYPE_BACKPACK', [4463, -242, 1743], 'A600RXM', False]
0:06:49.344618 received: ['TYPE_BACKPACK', [9424, -667, 2077], 'A600RXM', False]
0:19:24.083474 received: ['TYPE_VENT', [22373, -9011, 2064], 'A600RXM', False]
...
```
a prave pozice toho ventilatoru je
```
- event:
  id: 21
  type: artifact_report_attempt
  time_sec: 195
  reported_pose_world_frame: 11.87 -9.01 2.06
  reported_pose_artifact_frame: 22.37 -9.01 2.06
  reported_artifact_type: TYPE_VENT
  closest_artifact_name: vent_1
  distance: 9.89031
  points_scored: 0
  total_score: 1 
```
![filans-p2-vent-map](https://user-images.githubusercontent.com/5664353/113817185-3a00d400-9776-11eb-8bc8-73bcd67a99e3.jpg)
... tj. mapka vypada celkem rozumne a neni ulitla o 10m?!
