### ISSUE TITLE
TC4 - ver105opt2tc4r3 - 0ebd844c-a33e-49f5-b105-8706a1e37768

### ISSUE THREAD

**Issue by m3d** [robotika/subt-artf#145]
* 2x Freyja A2700L a B2700R
* score 12 bodu

tj. zatim nase nevyssi skore, takze si skoro to issue zaslouzi ;)

**Comment by m3d** [comment]
```
B2700R__breadcrumb___0: 29.74 -0.32 0.00
B2700R__breadcrumb___1: 59.77 -0.34 0.00
B2700R__breadcrumb___2: 69.68 -28.45 0.00
A2700L__breadcrumb___0: 69.62 27.87 0.00
B2700R__breadcrumb___3: 69.64 -58.26 0.00
A2700L__breadcrumb___1: 42.15 39.51 0.00
B2700R__breadcrumb___4: 90.70 -0.35 0.00
B2700R__breadcrumb___5: 120.73 -0.35 0.00
A2700L__breadcrumb___2: 69.59 58.89 0.00
A2700L__breadcrumb___3: 96.88 40.36 0.00
A2700L__breadcrumb___4: 126.91 40.35 0.00
A2700L__breadcrumb___5: 149.59 59.91 0.00
min x: -6.00 y: -66.00
max x: 1576.80 y: 86.00
width: 15868px height: 1560px
```
![state tlog](https://user-images.githubusercontent.com/5664353/115777777-0220a000-a3b6-11eb-91d4-aeacb74af33c.png)

**Comment by m3d** [comment]
Je to kompletni zmapovani sveta, dokonce s rezervou, kdy nektere casti videli oba roboti.

**Comment by m3d** [comment]
![tc4-12pts-teambase](https://user-images.githubusercontent.com/5664353/115778146-7f4c1500-a3b6-11eb-85d2-317f9f931448.png)
tj. dosah breadcrumbs je celkem maly = nedostatecny. Jinak jsou tam nejak v pravidelnem rozestupu vrtacky ;) @tajgr

**Comment by m3d** [comment]
`python -m osgar.tools.lidarview --pose2d app.pose2d --lidar depth2scan.scan --keyframes detector.localized_artf --title rosmsg.sim_time_sec logs\aws\tunnel\TC4\ver105-score12\A2700L.log --rgbd detector_rear.debug_rgbd`

![saveX-0000](https://user-images.githubusercontent.com/5664353/115823147-155b5c00-a406-11eb-9154-f7801f7e3579.jpg)

**Comment by m3d** [comment]
A2700L ma v logu 6h simulace a 1400 sim sec:
![tc4-map](https://user-images.githubusercontent.com/5664353/115823938-80f1f900-a407-11eb-9d59-c0aa20e21b66.jpg)

**Comment by m3d** [comment]
Teambase z nejakeho duvodu zachytila jenom zlomek komunikace:
```
0:04:17.365810 received: ['TYPE_DRILL', [29749, -387, 5], 'A2700L', False]
0:06:19.612427 received: ['TYPE_DRILL', [59815, -222, 21], 'A2700L', False]
0:11:18.695973 received: ['TYPE_EXTINGUISHER', [70123, -67348, 460], 'B2700R', True]
0:11:21.413676 received: ['TYPE_DRILL', [70047, -67332, 231], 'B2700R', False]
0:12:00.277074 received: ['TYPE_DRILL', [69683, -58285, 6], 'B2700R', False]
0:14:42.916554 received: ['TYPE_DRILL', [40056, 39042, 4], 'A2700L', None]
0:14:42.917354 received: ['TYPE_DRILL', [69835, -29123, 24], 'B2700R', None]
0:16:27.972334 received: ['TYPE_DRILL', [69835, -29123, 24], 'B2700R', False]
0:16:28.216290 received: ['TYPE_DRILL', [40056, 39042, 4], 'A2700L', False]
1:01:55.051121 received: ['TYPE_DRILL', [69716, 60195, 50], 'A2700L', None]
1:01:55.051121 received: ['TYPE_RESCUE_RANDY', [151064, 83028, 337], 'A2700L', None]
1:01:55.051121 received: ['TYPE_DRILL', [149784, 61492, 28], 'A2700L', None]
1:01:55.051121 received: ['TYPE_DRILL', [128432, 40271, 73], 'A2700L', None]
1:01:55.051121 received: ['TYPE_DRILL', [124386, 40257, 35], 'A2700L', None]
1:01:55.051121 received: ['TYPE_DRILL', [98093, 40451, -27], 'A2700L', None]
1:01:55.051121 received: ['TYPE_DRILL', [69692, 28965, 42], 'A2700L', None]
1:01:55.093162 received: ['TYPE_RESCUE_RANDY', [151064, 83028, 337], 'A2700L', True]
1:01:55.093877 received: ['TYPE_DRILL', [149784, 61492, 28], 'A2700L', False]
1:01:55.873492 received: ['TYPE_DRILL', [128432, 40271, 73], 'A2700L', False]
1:01:55.874173 received: ['TYPE_DRILL', [124386, 40257, 35], 'A2700L', False]
1:01:55.874966 received: ['TYPE_DRILL', [98093, 40451, -27], 'A2700L', False]
1:01:55.875743 received: ['TYPE_DRILL', [69692, 28965, 42], 'A2700L', False]
1:01:55.876546 received: ['TYPE_DRILL', [69716, 60195, 50], 'A2700L', False]
1:07:08.136823 received: ['TYPE_DRILL', [90269, -398, -16], 'A2700L', None]
```
Ale jsou tam videt ty False vrtacky/breadcrumbs.

**Comment by tajgr** [comment]
> Jinak jsou tam nejak v pravidelnem rozestupu vrtacky ;) @tajgr

Tak jo :-). Řešil bych to primárně doplněním trénovacích dat. Breadcrumbs tam máme jen pár, a jen z cave. Leccos by se také mohlo vyřešit naladěním thresholdů (snad již brzy).

**Comment by jisa** [comment]
Vzhledem k tomu, ze posledni trenovani mdnetu bezelo pomerne dlouho, zbyva nam cas tak na jednu iteraci uplneho pretrenovani. Tj. jestli neco potrebujeme pridat do trenovacich dat, bude potreba dat to na jeden pokus.

**Comment by m3d** [comment]
Za mne je je prijatelny hotfix na filtrovani breadcrumbs - vlastne by se mi libilo, abychom je umeli rozpoznat, ale souhlasim, ze jsou minimalne barevne stejne s vrtackou.

**Comment by jisa** [comment]
Asi se taky spis priklanim k hotfixu. Nicmene ten nemusi fungovat v pripadech, kdy robot breadcrumb po vypusteni posouva sem a tam, coz Freyja obcas dela. Pak nevime, kde ten breadcrumb vlastne je.

**Comment by m3d** [comment]
Toto info mi take prijde zajimave:
```
closest_artifact_report:
  name: rescue_randy_1
  type: TYPE_RESCUE_RANDY
  true_pos: 161.128 83.0188 0.39217
  reported_pos: 161.06 83.03 0.34
  distance: 0.08627775493697466
first_artifact_report: 110.448
last_artifact_report: 2930.02
mean_time_between_successful_artifact_reports: 256.3247272727273
greatest_distance_traveled: 5852.636835950343
greatest_distance_traveled_robot: B2700R
greatest_euclidean_distance_from_start: 1575.953416344078
greatest_euclidean_distance_from_start_robot: B2700R
total_distance_traveled: 11651.51510350409
greatest_max_vel: 2.411270523090993
greatest_max_vel_robot: B2700R
greatest_avg_vel: 2.281213912196342
greatest_avg_vel_robot: B2700R 
```
tj. mel na navrat 15min, ale jeste mu 10 min zbylo jako rezerva :) [last report]
a tech 11km spolecne ujetych je take dobre :)

**Comment by m3d** [comment]
toto je ale horsi:
```
artifacts_found: 12
artifact_report_count: 40
duplicate_report_count: 40 
```
a v jinem reportu
```
- event:
  id: 401
  type: artifact_report_limit_reached
  time_sec: 2930
  total_score: 12 
```
tj. tem robotum dosly pokusy!
Nelze tedy vyloucit, ze meli jeste nejake dalsi vzorky k reportovani??
(a celkove to bylo tedy "zariznuto")
