### ISSUE TITLE
CS3 - ver109dro3mcs3r1 - 0a7fafae-c1ec-46aa-b785-49bdaa5785b3

### ISSUE THREAD

**Issue by m3d** [robotika/subt-artf#153]
Pokus v jeskyni s letem v 3m (dve drony), ktery skoncil kolizi obou:
```
- event:
  id: 16
  type: collision
  time_sec: 211
  robot: A1C800L 
```
a druha
```
- event:
  id: 70
  type: collision
  time_sec: 1265
  robot: B10W1C800R
- event:
  id: 71
  type: dead_battery
  time_sec: 1362
  robot: B10W1C800R 
```
