### ISSUE TITLE
CC8 - ver111height3cc8r1 - e80d056f-b94a-49e1-9118-fc9944dfd253

### ISSUE THREAD

**Issue by m3d** [robotika/subt-artf#156]
Dve Pam drony. Leva narazila a prava se nejak lekla a vratila se na zakladnu:
```
- event:
  id: 7
  type: collision
  ke: 19.33
  ke_threshold: 8.36606
  link: base_link
  time_sec: 158
  robot: A1C600L
```
