### ISSUE TITLE
CP3 - ver118cp3r1 - 37ed4753-37fa-4403-8c5a-6807ee1d3d4f

### ISSUE THREAD

**Issue by m3d** [robotika/subt-artf#166]
2x Freyja `A900L` a `B900R s nejnovejsim `ver118` z masteru - s postrani detekci - 0 bodu

**Comment by m3d** [comment]
```
- event:
  id: 15
  type: artifact_report_attempt
  time_sec: 193
  reported_pose_world_frame: 93.96 13.34 -9.46
  reported_pose_artifact_frame: 83.96 13.34 -9.46
  reported_artifact_type: TYPE_HELMET
  closest_artifact_name: helmet_1
  distance: 19.57
  points_scored: 0
  total_score: 0
```

```
- event:
  id: 28
  type: artifact_report_attempt
  time_sec: 249
  reported_pose_world_frame: 104.45 35.71 -9.72
  reported_pose_artifact_frame: 94.45 35.71 -9.72
  reported_artifact_type: TYPE_HELMET
  closest_artifact_name: helmet_1
  distance: 30.721
  points_scored: 0
  total_score: 0
```
```
- event:
  id: 48
  type: artifact_report_attempt
  time_sec: 480
  reported_pose_world_frame: 119.54 34.42 -9.69
  reported_pose_artifact_frame: 109.54 34.42 -9.69
  reported_artifact_type: TYPE_HELMET
  closest_artifact_name: helmet_1
  distance: 44.4299
  points_scored: 0
  total_score: 0
```
pak tam byl jeste backpack, ale ten byl urcite spatne (268m)
