### ISSUE TITLE
P1 - ver80rc1p1 - cb38d467-8aa8-483b-99ce-9e537a6e20fb

### ISSUE THREAD

**Issue by m3d** [robotika/subt-artf#22]
2x drona, 2x Freyja - ale zatim to vypada, ze Freyja zase nevyhazuje breadcrumbs

**Comment by m3d** [comment]
```
- event:
  id: 38
  type: breadcrumb_deploy
  time_sec: 344
  robot: D40W600L 
```
tj. minimalne druha Freyja vyhazovala (a prvni tam opravdu nema zadny zaznam)
