### ISSUE TITLE
P1 - ver87cp1r1 - 54c166de-3269-4640-8a28-3c157ff2890c

### ISSUE THREAD

**Issue by m3d** [robotika/subt-artf#56]
Beh vsech robotu s nejnovejsim image `ver87` ve svete, kde jsme drive dostaly i 4 body ... ale ted to byly pouze body 2! (ano je to vice nez nula = ukol splnen, ale jel tam kolem mnoha artefaktu a nedopadlo to).

![state tlog](https://user-images.githubusercontent.com/5664353/96169784-f645b400-0f22-11eb-9f82-38d90010b7b8.png)

**Comment by m3d** [comment]
```
artifacts_found: 2 
artifact_report_count: 13
duplicate_report_count: 1598
closest_artifact_report:
  name: rescue_randy_4
  type: TYPE_RESCUE_RANDY
  true_pos: 393.968 -149.947 -26.8088
  reported_pos: 393.52 -152.81 -26.63
  distance: 2.903023342574064 
```
podle mnozstvi duplikatu mam pocit, ze neco nefunguje. Zajimave treba je, ze teambase T1800 ma jenom jeden potvrzeny artefakt:
```
8:52:45.258764 24 [b'F1000W600RH400L3600W', b"['TYPE_RESCUE_RANDY', [383518, -152809, -26628], 'A100W900LH700R3600W', True]\n"]
```
