### ISSUE TITLE
P3 - ver88influence2cp3r1 - 201d5768-a67a-40d4-9d41-6fd152af6556

### ISSUE THREAD

**Issue by zwn** [robotika/subt-artf#61]
Drona A150L letěla na dvojzub, kde většinou štrejchla a ztratila se.

**Comment by zwn** [comment]
![state tlog](https://user-images.githubusercontent.com/1130051/96198773-04f98e80-0f56-11eb-8d1a-d6304da2e318.png)

**Comment by zwn** [comment]
![image](https://user-images.githubusercontent.com/1130051/96198788-12af1400-0f56-11eb-94eb-ee82791ba03c.png)

<pre>Processing logfile: aws-ver88influence2cp3r1-A150L.log
  Autodetected name: A150L
  Autodetect pose3d stream: offseter.pose3d
  Trace reduced count: 316
  Ground truth seconds: 427
  sim_time_sec:   180, error:  1.05m, distance:   46.37m from origin, path:   63.67m
  Maximum error: 1.39m -&gt; OK
</pre>

**Comment by zwn** [comment]
```yml
closest_artifact_report:
  name: helmet_1
  type: TYPE_HELMET
  true_pos: 76.7828 22.5281 -7.58803
  reported_pos: 75.77 22.95 -7.59
  distance: 1.097123119646503
```
