### ISSUE TITLE
P2 - ver92cp2r1 - e21c79cf-bd7c-4012-bdd9-7cd6f461602a

### ISSUE THREAD

**Issue by m3d** [robotika/subt-artf#63]
kompletni run s 8mi roboty, 1 bod

**Comment by m3d** [comment]
```
artifact_report_count: 16
duplicate_report_count: 122
closest_artifact_report:
  name: rescue_randy_4
  type: TYPE_RESCUE_RANDY
  true_pos: 211.557 151.474 -11.1313
  reported_pos: 211.1 152.44 -11.03
  distance: 1.07319221914747 
```
