### ISSUE TITLE
P2 - ver92cp2r2 - 6d0865aa-c923-4bfc-8bcb-ad87fcdb87f3

### ISSUE THREAD

**Issue by m3d** [robotika/subt-artf#65]
Minimalisticka verze drona A600L a Freyja B1500R na ziskani 2 bodu, ale nedaly to. Drona se minula i kdyz reportovala diky breadcrumbs pekne z dalky. Freyja zatim stale jede ...

**Comment by m3d** [comment]
0 bodu
![p2-freja-and-drone](https://user-images.githubusercontent.com/5664353/97142637-50374c80-1761-11eb-8c0f-58dfb7a5fb3d.png)
```
1:00:09.669940 received: ['TYPE_RESCUE_RANDY', [195696, 149197, -11024], 'A600L', False]
3:48:04.338595 received: ['TYPE_HELMET', [569692, 76293, -22788], 'B1500R', None]
3:48:04.406460 received: ['TYPE_HELMET', [583448, 76916, -24678], 'B1500R', None]
3:48:04.407097 received: ['TYPE_HELMET', [569692, 76293, -22788], 'B1500R', False]
3:49:19.005418 received: ['TYPE_HELMET', [583448, 76916, -24678], 'B1500R', False]
maximum delay: 0:00:00.000169
Robot IDs ['A600L', 'B1500R']
```

**Comment by m3d** [comment]
Drona se pri navratu zasekla, Randyho cestou tam nevidela (cas ~ 41:01) a na ceste zpet.

**Comment by m3d** [comment]
Behem preletu se absolutni lokace artefaktu (stale RANDY) od prvniho reportu lisila nejvyse `0.2168m`, tj. snad skladani pozice z kamery a pozice robota je OK.

**Comment by m3d** [comment]
```
>>> distance3D([195.696, 149.197, -11.024], [201.63, 151.32, -11.49])
6.319544366487186
```
tj. chyba je hlavne v X-ove souradnici

**Comment by m3d** [comment]
```
>>> distance3D([579.53, 74.95, -24.93], [569.692, 76.293, -22.788])
10.157660015968212
>>> distance3D([579.53, 74.95, -24.93], [583.448, 76.916, -24.678])
4.390829534381861
```
hmm, tak tomu nerozumim :( ... nemeli bychom za ten druhy report dostat bod?!

**Comment by m3d** [comment]
```
python subt\tools\ignstate.py -a logs\aws\P2\ver92cp2r2\state.tlog
rescue_randy    [590.6, 170.81, -4.23]
rope            [259.87, -352.27, -54.4]
backpack        [483.39, -577.02, 0.42]
helmet          [468.8, -129.4, 73.55]
helmet          [533.09, -439.5, -8.79]
rescue_randy    [652.25, -136.91, 19.68]
rescue_randy    [788.19, -582.51, -26.54]
helmet          [297.67, 269.27, -24.23]
helmet          [899.64, -301.68, -109.78]
rope            [373.98, -61.37, 43.22]
rescue_randy    [201.63, 151.32, -11.49]
backpack        [924.3, 4.95, -54.11]
helmet          [579.53, 74.95, -24.93]
backpack        [521.62, -66.02, 81.6]
rope            [652.38, 370.19, -45.08]
rope            [299.48, 130.22, 2.01]
phone           [561.81, 452.33, -48.97]
phone           [349.1, 27.59, 101.5]
phone           [677.61, -366.81, -115.81]
phone           [847.57, 374.99, -27.74]
```

**Comment by m3d** [comment]
par poznamek k event logu:
```
- event:
  id: 34
  type: artifact_report_attempt
  time_sec: 662
  reported_pose: 205.7 149.2 -11.02
  reported_artifact_type: TYPE_RESCUE_RANDY
  closest_artifact_name: rescue_randy_4
  distance: 6.2837
  points_scored: 0
  total_score: 0 
```
to je asi OK, resp. to sedi s tim co vime

```
- event:
  id: 67
  type: artifact_report_attempt
  time_sec: 2060
  reported_pose: 593.45 76.92 -24.68
  reported_artifact_type: TYPE_HELMET
  closest_artifact_name: helmet_1
  distance: 255.748
  points_scored: 0
  total_score: 0 
```
ale reportovat to ma `helmet_5`?!
