### ISSUE TITLE
U1 - ver92u1 - 575f5c5d-588c-432e-bb54-6a0cd6a9808f

### ISSUE THREAD

**Issue by m3d** [robotika/subt-artf#66]
Test jak se chovaji dve drony (A600L a B10W600R) v Urban svete. Navic to byl soutezni svet, ktery jsem poradne nevidel. Score 1 bod, i kdyz proleteli okolo vice (nekolik falesnych reportu). B drona se zasekla pod schody (pri navratu po 3D trajektorii), ale nakonec se nejak vymotala a skoncila v posledni zatacce do staging area.
OT maji tam bug s Teambase lokaci (osrf-subt-690).

Jinak je to neco jako tovarni hala:
![u1-overview](https://user-images.githubusercontent.com/5664353/97674797-68bfa380-1a8e-11eb-9095-78783a9dd269.jpg)

**Comment by m3d** [comment]
Kupodivu nedostal bod za batoh hned v uvodni chodbe, ale za Randyho nekde hloubeji:
```
artifact_report_count: 11
duplicate_report_count: 116
closest_artifact_report:
  name: rescue_randy_1
  type: TYPE_RESCUE_RANDY
  true_pos: 67.9463 -12.9255 1.31217
  reported_pos: 69.09 -11.92 1.42
  distance: 1.526688644591521 
```
