### ISSUE TITLE
U1 - ver93stageuc1r1 - b968d362-3115-4a23-812f-03595407c0f0

### ISSUE THREAD

**Issue by m3d** [robotika/subt-artf#79]
V tomto behu "zakufrovala" drona B a tedy 3 body ziskala pouze drona A. Novy bod je za batoh v uvodni casti.
![state tlog](https://user-images.githubusercontent.com/5664353/98442092-ede82f80-2102-11eb-9d71-dd1e92633461.png)
```
0:04:05.266471 received: ['TYPE_BACKPACK', [-45340, 11983, -2931], 'A600L', True]
```
... "zajimave" je teambase nedostala dalsi bodovane reporty, ale to je tim, ze je "vytrcena" mimo (nejspise).
```
- event:
  id: 2
  type: artifact_report_attempt
  time_sec: 153
  reported_pose: -27.84 38.98 4.57
  reported_artifact_type: TYPE_BACKPACK
  closest_artifact_name: backpack_1
  distance: 0.266268
  points_scored: 1
  total_score: 1 
- event:
  id: 13
  type: artifact_report_attempt
  time_sec: 380
  reported_pose: 68.36 -12.66 1.5
  reported_artifact_type: TYPE_RESCUE_RANDY
  closest_artifact_name: rescue_randy_1
  distance: 0.526258
  points_scored: 1
  total_score: 2 
- event:
  id: 31
  type: artifact_report_attempt
  time_sec: 700
  reported_pose: 64.71 16.55 -7.08
  reported_artifact_type: TYPE_GAS
  closest_artifact_name: gas_1
  distance: 2.20909
  points_scored: 1
  total_score: 3 
```
