### ISSUE TITLE
CC - 01 - skóre 5

### ISSUE THREAD

**Issue by zwn** [robotika/subt-artf#97]
<pre>min x: -8.01 y: -301.31
max x: 487.08 y: 752.65
width: 4990px height: 10579px
Ground truth count: 903817
Processing logfile: a100w900lh700rh3600w.log
  Autodetected name: A100W900LH700RH3600W
  Autodetect pose3d stream: offseter.pose3d
  Trace reduced count: 1219
  Ground truth seconds: 3609
  sim_time_sec:   166, error:  1.01m, distance:   26.55m from origin, path:   44.01m
  sim_time_sec:   540, error:  2.03m, distance:  204.92m from origin, path:  387.12m
  sim_time_sec:   620, error:  5.28m, distance:  190.29m from origin, path:  463.54m
  Maximum error: 33.77m -&gt; FAIL
Processing logfile: b700w600lh400rh3600w.log
  Autodetected name: B700W600LH400RH3600W
  Autodetect pose3d stream: offseter.pose3d
  Trace reduced count: 1924
  Ground truth seconds: 3609
  sim_time_sec:   866, error:  1.14m, distance:   94.10m from origin, path:  146.06m
  sim_time_sec:   893, error:  2.13m, distance:  114.26m from origin, path:  175.93m
  sim_time_sec:  1104, error:  4.61m, distance:  182.06m from origin, path:  371.55m
  sim_time_sec:  1105, error:  7.82m, distance:  181.79m from origin, path:  372.57m
  Maximum error: 205.16m -&gt; FAIL
Processing logfile: c120w1500rh1300lh3600w.log
  Autodetected name: C120W1500RH1300LH3600W
  Autodetect pose3d stream: offseter.pose3d
  Trace reduced count: 1626
  Ground truth seconds: 3609
  sim_time_sec:   180, error:  1.16m, distance:   31.76m from origin, path:   45.76m
  sim_time_sec:   184, error:  2.30m, distance:   31.80m from origin, path:   45.81m
  sim_time_sec:   187, error:  3.17m, distance:   31.80m from origin, path:   45.85m
  sim_time_sec:   354, error:  4.38m, distance:   32.74m from origin, path:   63.63m
  sim_time_sec:   356, error:  5.43m, distance:   32.74m from origin, path:   63.63m
  Maximum error: 7800.73m -&gt; FAIL
Processing logfile: commsbridge.tar.gz.log
  Autodetected name: A100W900LH700RH3600W
  Autodetect pose3d stream: offseter.pose3d
  Trace reduced count: 410
  Ground truth seconds: 3609
  sim_time_sec:   166, error:  1.01m, distance:   26.55m from origin, path:   44.01m
  Maximum error: 1.33m -&gt; OK
Processing logfile: d0w1700rh1500lh3600w.log
  Autodetected name: D0W1700RH1500LH3600W
  Autodetect pose3d stream: offseter.pose3d
  Trace reduced count: 2728
  Ground truth seconds: 3609
  sim_time_sec:    67, error:  1.03m, distance:   29.70m from origin, path:   44.01m
  sim_time_sec:   912, error:  2.02m, distance:  226.54m from origin, path:  879.18m
  sim_time_sec:  1001, error:  6.65m, distance:  193.14m from origin, path:  980.43m
  Maximum error: 33156.76m -&gt; FAIL
Processing logfile: e60w1750lh1550rh3600w.log
  Autodetected name: E60W1750LH1550RH3600W
  Autodetect pose3d stream: offseter.pose3d
  Trace reduced count: 2955
  Ground truth seconds: 3609
  sim_time_sec:   226, error:  1.69m, distance:  103.60m from origin, path:  151.24m
  sim_time_sec:   227, error:  2.47m, distance:  103.67m from origin, path:  151.36m
  sim_time_sec:   228, error:  3.12m, distance:  103.71m from origin, path:  151.43m
  sim_time_sec:   234, error:  4.58m, distance:  103.91m from origin, path:  152.06m
  sim_time_sec:   235, error:  5.54m, distance:  103.89m from origin, path:  152.20m
  Maximum error: 204.68m -&gt; FAIL
Processing logfile: f1000w600rh400lh3600w.log
  Autodetected name: F1000W600RH400LH3600W
  Autodetect pose3d stream: offseter.pose3d
  Trace reduced count: 2254
  Ground truth seconds: 3609
  sim_time_sec:  1482, error:  1.08m, distance:  223.87m from origin, path:  414.99m
  sim_time_sec:  1905, error:  2.04m, distance:  166.25m from origin, path:  801.03m
  sim_time_sec:  2093, error:  3.04m, distance:   87.19m from origin, path:  970.72m
  sim_time_sec:  2263, error:  6.87m, distance:   76.93m from origin, path:  986.40m
  Maximum error: 37.91m -&gt; FAIL
Processing logfile: g300w900rh700lh3600w.log
  Autodetected name: G300W900RH700LH3600W
  Autodetect pose3d stream: offseter.pose3d
  Trace reduced count: 1550
  Ground truth seconds: 3609
  sim_time_sec:   757, error:  1.00m, distance:  208.09m from origin, path:  380.64m
  sim_time_sec:  1485, error:  2.00m, distance:  190.05m from origin, path: 1065.98m
  sim_time_sec:  1564, error: 11.10m, distance:  233.42m from origin, path: 1141.80m
  Maximum error: 11.10m -&gt; FAIL
Processing logfile: h0w1050rh850lh3600w.log
  Autodetected name: H0W1050RH850LH3600W
  Autodetect pose3d stream: offseter.pose3d
  Trace reduced count: 3017
  Ground truth seconds: 3609
  sim_time_sec:   386, error:  1.02m, distance:  171.17m from origin, path:  315.74m
  sim_time_sec:   449, error:  2.03m, distance:  204.55m from origin, path:  367.64m
  sim_time_sec:   527, error:  3.06m, distance:  228.30m from origin, path:  440.85m
  sim_time_sec:   819, error:  4.17m, distance:  285.86m from origin, path:  668.89m
  sim_time_sec:   913, error:  5.02m, distance:  331.02m from origin, path:  739.60m
  Maximum error: 64217.96m -&gt; FAIL
Processing logfile: t4000.log
  Autodetected name: T4000
  skiping teambase
</pre>
![Screenshot from 2020-11-23 08-48-08](https://user-images.githubusercontent.com/1130051/99939503-7c4aeb00-2d6a-11eb-8a19-7934ad64adc4.png)
![Screenshot from 2020-11-23 08-50-06](https://user-images.githubusercontent.com/1130051/99939506-7ce38180-2d6a-11eb-9236-02c87f98cdd0.png)
![Screenshot from 2020-11-23 08-51-18](https://user-images.githubusercontent.com/1130051/99939508-7d7c1800-2d6a-11eb-9c25-293d6dfe07bc.png)
![Screenshot from 2020-11-23 08-51-36](https://user-images.githubusercontent.com/1130051/99939509-7e14ae80-2d6a-11eb-90c0-d256ac15fc65.png)
![Screenshot from 2020-11-23 08-52-30](https://user-images.githubusercontent.com/1130051/99939510-7ead4500-2d6a-11eb-8711-6be6aa86d65a.png)
![Screenshot from 2020-11-23 08-53-28](https://user-images.githubusercontent.com/1130051/99939511-7f45db80-2d6a-11eb-8fbb-171c297119a6.png)
![Screenshot from 2020-11-23 08-54-22](https://user-images.githubusercontent.com/1130051/99939513-7fde7200-2d6a-11eb-8bb8-5d1a6401c171.png)
![Screenshot from 2020-11-23 08-54-48](https://user-images.githubusercontent.com/1130051/99939514-7fde7200-2d6a-11eb-940d-e52fa129e097.png)
![Screenshot from 2020-11-23 08-55-57](https://user-images.githubusercontent.com/1130051/99939516-80770880-2d6a-11eb-9d9a-5667df7c0e13.png)

**Comment by zwn** [comment]
```yaml
world_name: cave_circuit_01
robots:
  A100W900LH700RH3600W:
    platform: X4
    config: SSCI_X4_SENSOR_CONFIG_2
  B700W600LH400RH3600W:
    platform: X4
    config: SSCI_X4_SENSOR_CONFIG_2
  C120W1500RH1300LH3600W:
    platform: FREYJA
    config: ROBOTIKA_FREYJA_SENSOR_CONFIG_2
  D0W1700RH1500LH3600W:
    platform: FREYJA
    config: ROBOTIKA_FREYJA_SENSOR_CONFIG_2
  E60W1750LH1550RH3600W:
    platform: FREYJA
    config: ROBOTIKA_FREYJA_SENSOR_CONFIG_2
  F1000W600RH400LH3600W:
    platform: X4
    config: SSCI_X4_SENSOR_CONFIG_2
  G300W900RH700LH3600W:
    platform: X4
    config: SSCI_X4_SENSOR_CONFIG_2
  H0W1050RH850LH3600W:
    platform: X4
    config: SSCI_X4_SENSOR_CONFIG_2
marsupials:
  {}
artifacts_found: 5
robot_count: 8
unique_robot_count: 2
sim_time: 3600
real_time: 103760
artifact_report_count: 19
duplicate_report_count: 1242
closest_artifact_report:
  name: helmet_1
  type: TYPE_HELMET
  true_pos: 50.2529 53.7816 0.005113
  reported_pos: 50.87 53.86 -0.11
  distance: 0.6326199295616853
first_artifact_report: 168.144
last_artifact_report: 970.004
mean_time_between_successful_artifact_reports: 160.372
greatest_distance_traveled: 1224.949031793235
greatest_distance_traveled_robot: D0W1700RH1500LH3600W
greatest_euclidean_distance_from_start: 435.8400062627277
greatest_euclidean_distance_from_start_robot: H0W1050RH850LH3600W
total_distance_traveled: 6560.744402364375
greatest_max_vel: 10.56578766983759
greatest_max_vel_robot: D0W1700RH1500LH3600W
greatest_avg_vel: 8.872257844656614
greatest_avg_vel_robot: D0W1700RH1500LH3600W
greatest_elevation_gain: 130
greatest_elevation_gain_robot: D0W1700RH1500LH3600W
greatest_elevation_loss: -130
greatest_elevation_loss_robot: D0W1700RH1500LH3600W
total_elevation_gain: 320
total_elevation_loss: -380
max_elevation_reached: 20
max_elevation_reached_robot: D0W1700RH1500LH3600W
min_elevation_reached: -30
min_elevation_reached_robot: A100W900LH700RH3600W
```
