### ISSUE TITLE
CC - 02 - skóre 2

### ISSUE THREAD

**Issue by zwn** [robotika/subt-artf#99]
```yaml
world_name: cave_circuit_01
robots:
  A100W900LH700RH3600W:
    platform: X4
    config: SSCI_X4_SENSOR_CONFIG_2
  B700W600LH400RH3600W:
    platform: X4
    config: SSCI_X4_SENSOR_CONFIG_2
  C120W1500RH1300LH3600W:
    platform: FREYJA
    config: ROBOTIKA_FREYJA_SENSOR_CONFIG_2
  D0W1700RH1500LH3600W:
    platform: FREYJA
    config: ROBOTIKA_FREYJA_SENSOR_CONFIG_2
  E60W1750LH1550RH3600W:
    platform: FREYJA
    config: ROBOTIKA_FREYJA_SENSOR_CONFIG_2
  F1000W600RH400LH3600W:
    platform: X4
    config: SSCI_X4_SENSOR_CONFIG_2
  G300W900RH700LH3600W:
    platform: X4
    config: SSCI_X4_SENSOR_CONFIG_2
  H0W1050RH850LH3600W:
    platform: X4
    config: SSCI_X4_SENSOR_CONFIG_2
marsupials:
  {}
artifacts_found: 2
robot_count: 8
unique_robot_count: 2
sim_time: 3600
real_time: 100785
artifact_report_count: 3
duplicate_report_count: 0
closest_artifact_report:
  name: phone_4
  type: TYPE_PHONE
  true_pos: 41.0684 -2.15762 0.154551
  reported_pos: 41.52 -0.77 0.04
  distance: 1.463746442490428
first_artifact_report: 282.092
last_artifact_report: 340.244
mean_time_between_successful_artifact_reports: 29.07600000000002
greatest_distance_traveled: 1176.129336714539
greatest_distance_traveled_robot: H0W1050RH850LH3600W
greatest_euclidean_distance_from_start: 347.2261813280152
greatest_euclidean_distance_from_start_robot: F1000W600RH400LH3600W
total_distance_traveled: 5401.276036852953
greatest_max_vel: 8.408200276188603
greatest_max_vel_robot: H0W1050RH850LH3600W
greatest_avg_vel: 6.295096309486628
greatest_avg_vel_robot: H0W1050RH850LH3600W
greatest_elevation_gain: 45
greatest_elevation_gain_robot: G300W900RH700LH3600W
greatest_elevation_loss: -45
greatest_elevation_loss_robot: G300W900RH700LH3600W
total_elevation_gain: 165
total_elevation_loss: -220
max_elevation_reached: 25
max_elevation_reached_robot: H0W1050RH850LH3600W
min_elevation_reached: -30
min_elevation_reached_robot: A100W900LH700RH3600W
```
